version: '3.9' 

services:
  postgres:
    image: postgres:latest 
    container_name: postgres-container 
    environment:
      POSTGRES_USER: ujjwal
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testDB
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
    driver: local
